# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_login_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 661)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(24, 24, 36)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_edit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login_edit.setFont(font)
        self.login_edit.setStyleSheet("color: white;\n"
"border-bottom: 3px solid rgb(230, 5, 64);")
        self.login_edit.setObjectName("login_edit")
        self.verticalLayout_2.addWidget(self.login_edit)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.password_edit = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("color: white;\n"
"border-bottom: 3px solid rgb(230, 5, 64)")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.verticalLayout_3.addWidget(self.password_edit)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(200, 149))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.submit_btn = QtWidgets.QPushButton(self.frame_3)
        self.submit_btn.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submit_btn.setFont(font)
        self.submit_btn.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(230, 5, 64);\n"
"border-radius: 6px;\n"
"color: rgb(128, 128, 128)\n"
"}\n"
"QPushButton:hover{\n"
"border: 3px solid rgb(230, 5, 64);\n"
"border-radius: 6px;\n"
"color: rgb(128, 128, 128);\n"
"background-color: rgba(230, 5, 64, 70)\n"
"}")
        self.submit_btn.setObjectName("submit_btn")
        self.verticalLayout_4.addWidget(self.submit_btn)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(128, 128, 128)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.caretaker_btn = QtWidgets.QPushButton(self.frame_3)
        self.caretaker_btn.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.caretaker_btn.setFont(font)
        self.caretaker_btn.setStyleSheet("QPushButton{\n"
"border: 3px solid rgb(230, 5, 64);\n"
"border-radius: 6px;\n"
"color: rgb(128, 128, 128)\n"
"}\n"
"QPushButton:hover{\n"
"border: 3px solid rgb(230, 5, 64);\n"
"border-radius: 6px;\n"
"color: rgb(128, 128, 128);\n"
"background-color: rgba(230, 5, 64, 70)\n"
"}")
        self.caretaker_btn.setObjectName("caretaker_btn")
        self.verticalLayout_4.addWidget(self.caretaker_btn)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.login_edit.setPlaceholderText(_translate("MainWindow", "Login"))
        self.password_edit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.submit_btn.setText(_translate("MainWindow", "Submit"))
        self.label_3.setText(_translate("MainWindow", "Or"))
        self.caretaker_btn.setText(_translate("MainWindow", "Caretaker"))
